#!/bin/bash
set -e

DOC=$(stack path --local-doc-root)
COV=$(stack path --local-hpc-root)

stack test
stack haddock

rsync --delete "$DOC" doc/api
rsync --delete "$COV" doc/cov
git add --all doc/api doc/cov
