#!/bin/bash
set -e

DOC=$(stack path --local-doc-root)
COV=$(stack path --local-hpc-root)

stack test
stack haddock
stack test :hspec --coverage

rsync -a --delete "$DOC" doc/api
rsync -a --delete "$COV" doc/cov

git add --all doc/api doc/cov
